# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(default='a', max_length=2)),
                ('name', models.CharField(default='a', max_length=10)),
                ('example', models.CharField(default='car', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=100)),
                ('back', models.CharField(max_length=100)),
                ('flip', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.TextField()),
                ('category', models.CharField(default='grammar', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Koyla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('la', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
                ('grammarCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koyla.GrammarCard')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='grammarCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koyla.GrammarCard'),
        ),
    ]
