# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koyla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcard',
            name='category',
            field=models.TextField(default='grammar'),
        ),
    ]
