# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koyla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=30)),
                ('back', models.CharField(max_length=30)),
                ('flip', models.BooleanField(default=False)),
            ],
        ),
    ]
