# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koyla', '0002_grammarcard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarcard',
            name='category',
            field=models.CharField(default='grammar', max_length=64),
        ),
    ]
