# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koyla', '0003_auto_20170520_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(max_length=100),
        ),
    ]
