# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koyla', '0005_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
